---
- name: Install main user packages.
  package:
    name:
      - curl
      - htop
      - git
      - vim
      - nmap
      - kdeconnect
      - picard
      - qbittorrent
      - remmina
      - gnupg 
      - software-properties-common
    state: latest

- name: Install terraform
  vars:
    terraform_version: 1.2.4
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: Install vagrant
  vars: 
    vagrant_version: 2.2.19
  unarchive:
    src: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: Add chrome key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Add repository for chrome
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
  register: chrome_repo
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Update sources (repo added or changed)
  apt:
    update_cache: yes
  changed_when: False
  when: chrome_repo.changed

- name: Install chrome
  apt:
    name: google-chrome-stable
  when: ansible_distribution in ["Debian", "Ubuntu"]